### ISSUE TITLE
'proc_open(): unable to create pipe Too many open files

### ISSUE THREAD

**Issue by umpirsky** [box-project/box2#126] opened 2015-12-19 20:14 UTC
Using Box version `2.6.0` build `34259e688bad430cf6e4418d4682d7650c7b90f1` on https://github.com/umpirsky/Twig-Gettext-Extractor/pull/31 I got:

```
$ box.phar build 
Building...
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): unable to create pipe Too many open files' in phar:///usr/local/bin/box.phar/src/vendors/symfony/console/Application.php:978
Stack trace:
#0 [internal function]: KevinGH\Box\Application->KevinGH\Box\{closure}(2, 'proc_open(): un...', 'phar:///usr/loc...', 978, Array)
#1 phar:///usr/local/bin/box.phar/src/vendors/symfony/console/Application.php(978): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///usr/local/bin/box.phar/src/vendors/symfony/console/Application.php(788): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///usr/local/bin/box.phar/src/vendors/symfony/console/Application.php(749): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///usr/local/bin/box.phar/src/vendors/symfony/console/Application.php(679): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///usr/local/bin/box.phar/src/vendors/symfony/console/Application.php(133): Symfony\Component\Console\Applic in phar:///usr/local/bin/box.phar/src/vendors/symfony/console/Application.php on line 978
```

**Comment by kherge** [comment] 2015-12-19 22:48
Hi @umpirsky, I'm closing this issue as it is a duplicate of #80. If there is new information, please add it to that open issue.

Thanks!

**Closed as completed by kherge** 2015-12-19 22:48 UTC
